### ISSUE TITLE
Unable to add/activate the toolbar

### ISSUE THREAD

**Issue by AdmiralStipe** [KoalaBear84/HAClimateDeskBand#1]
**Describe the bug**
Install runs without problems, but the toolbar can not be activated although it is seen on the toolbar list. WIth a right click on a taskbar the addon is visible but I'm unable to select it (I click it, but nothing happens and the checkmark does not remain). 

**Expected behavior**
After installation the toolbar should be added with a right click on a taskbar and selecting "Ha Climate Deskband".

**Screenshots**
![toolbars](https://user-images.githubusercontent.com/64564398/104000218-37560900-519e-11eb-98d5-bb1a79d00e95.png)

**Install Log**
D:\CustomApps\HADeskBand>rem Check permissions

D:\CustomApps\HADeskBand>net session  1>nul 2>&1

D:\CustomApps\HADeskBand>if 0 == 0 (echo Administrative permissions confirmed. )  else (
echo Please run this script with administrator permissions.
 pause
 goto EXIT
)
Administrative permissions confirmed.

D:\CustomApps\HADeskBand>if defined ProgramFiles(x86) (set command=C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\regasm.exe )  else (set command=C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\regasm.exe )

D:\CustomApps\HADeskBand>C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\regasm.exe /nologo /codebase "HAClimateDeskband.dll"
RegAsm : warning RA0000 : Registering an unsigned assembly with /codebase can cause your assembly to interfere with other applications that may be installed on the same computer. The /codebase switch is intended to be used only with signed assemblies. Please give your assembly a strong name and re-register it.
Succesfully registered deskband `HA Climate DeskBand` - GUID: {ce5e3e5c-c896-4963-99c9-0df948ba092b}
Request to show deskband.
The deskband was Succesfully shown with taskbar.
You may see the alert notice box from explorer call.
Types registered successfully

D:\CustomApps\HADeskBand>pause
Press any key to continue . . .

**Desktop (please complete the following information):**
 - OS: Win10 Pro, 20H2, build 19042.685 (64bit)
 - HADeskBand Version 1.1.0.0

**Comment by KoalaBear84** [comment]
Hi,

Hmm, that is strange. All looks OK according to the logs. It also says "_The deskband was Succesfully shown with taskbar._"

Did you get this popup?

![](https://user-images.githubusercontent.com/5886900/103490074-9243d500-4e19-11eb-9523-7ae4cf649721.png)

The problem is that I don't have any idea how I can see what is wrong.

Also there is error handling everywhere so it should need to start in all sitations. And I see you have 64-bit which is also fine.

I could take a look to see if I can fix it by looking together with something like AnyDesk?

**Comment by AdmiralStipe** [comment]
Yes, I got the popup and confirmed it. As I wrote, it seems everything is OK, I just can not add the toolbar. 
I also tried rebooting, restarting Explorer service, modifying the installer (removing quotations, removing "/codebase", adding "/verbose" to see more details), but nothing worked. In all cases the install was seamingly OK, but without end-effect. 
I can't tell how the DLL is built, but could the problem be the language (as you could see from the screenshot I'm using localised Slovenian version of Windows, not the English one)? It shoudln't, but maybe some tiny little detail prevents it from showing up....

**Comment by KoalaBear84** [comment]
Hmm.. You have tried more than I could have expected! Luckily including rebooting and restarting explorer.exe 😇

Localization should not matter indeed. I do have tested it only on English. I'll try to test it in a Virtual Machine and see if it works. Somehow VirtualBox is very slow (already running and updating Windows I guess for 10 minutes..), probably because I have WSL2 (Linux on Windows) installed which already uses the hardware accelerated VM..

**Comment by KoalaBear84** [comment]
It's strange. Sometimes at a new computer, it doesn't show the dialog, and when you do Install for the second time it does.

In a Dutch [Windows Sandbox](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview) it works, but at the host, it doesn't and I have the some problem as you have, which is 'good', so I can figure out what goes wrong.

![](https://user-images.githubusercontent.com/5886900/104091036-1adbce80-527b-11eb-8745-9717400a446a.png)

To be continued.

**Comment by AdmiralStipe** [comment]
I don't want to be a pain in the ass, but I'm really keen on using this addon - any progress on troubleshooting the issue?

**Comment by KoalaBear84** [comment]
Haha. You are not. I just didn't look further enough. I like that I can help someone with it.

I'll try to look at it asap, and will let you know.

**Comment by KoalaBear84** [comment]
Yes! I probably fixed it. Strange that I never got this on my own desktop. Luckily it was reproducible on the laptop.

Looks like it had something to do when the DeskBand was resized before loading of the components on it was finished. Now I'll do nothing with controls before it's initialized.

Please test this version and let me know if it works :)

https://github.com/KoalaBear84/HAClimateDeskBand/releases/tag/v1.2.0.1

**Comment by AdmiralStipe** [comment]
Yes, now I can add it and set it up :). 

But... it kinda doesn't work :(. Now I have two new issues...
Shall I continue here or open a new issue (as these are not related to installation anymore) or are you fed up with my nagging :)?

**Comment by KoalaBear84** [comment]
**Edit**

Sorry, please make a new issue, it's better than continuing here.
