### ISSUE TITLE
Unable to control any thermostat

### ISSUE THREAD

**Issue by AdmiralStipe** [KoalaBear84/HAClimateDeskBand#2]
**Describe the bug**
Editing, as things change litteraly from minute to minute :). 

So, I can connect to HA and see all three thermostats, that I have implemented. But I can't control the temperature on any of them. Clicking (or CTRL-clicking) on the temperature has no effect, scrolling the mousewheel also not. But the click on fire icon (On/Off) works. 

Additionally, the plugin only works for two generic thermostats (a heater, connected to a smartplug and reading a temperature sensor in the room). When I try to control an "upgraded" thermostat, the measured temp and time turn red and the error "Error retreiving/updating values: Value can not be null. Parameter name: value" shows up. 
By "upgraded" thermostat I mean my actual A/C (Mitsubitshi), controlled by SmartIR (IR commands), which has more different hvac modes (off/heat/cool/dry) and also more status attributes as the generic one.

**Comment by AdmiralStipe** [comment]
After checking the code I guess I know, why the A/C is not working... you're reading the "hvac_action" attribute to find out, in which state the thermostat is... but my Mitsubishi is unfortunately not reporting it :(. 
Attached the comparsion of the attributes from a generic climate and the Mistubishi one: 

Mitsubishi:
hvac_modes: off, cool, heat, dry
min_temp: 18
max_temp: 30
target_temp_step: 1
fan_modes: low, med, high, auto
current_temperature: 22.6
temperature: 23
current_humidity: 46.4
fan_mode: high
last_on_operation: heat
device_code: 18868
manufacturer: Mitsubishi Heavy
supported_models: SRK35ZJX-S
supported_controller: Broadlink
commands_encoding: Base64
friendly_name: Living room
supported_features: 9


Generic:
hvac_modes: heat, off
min_temp: 20
max_temp: 30
current_temperature: 20.7
temperature: 21
hvac_action: heating
friendly_name: Bedroom
supported_features: 1

**Comment by KoalaBear84** [comment]
Thanks for checking. I was already creating a tool to get a response for this, but had other things (work) to do as well :)

Hmm, could "last\_on\_operation" be used instead?

Hmm, if so, it would stay on the fire icon even if the temperature is OK I guess? :P

**Comment by AdmiralStipe** [comment]
No prob, didn't mean to rush you in any way, just contributing info for easier problem solving :). 

Yeah, the problem in this case is, that the Mistubishi works in it's own way and even upon reaching the set temperature, the status does not change... it simply turns down the heater and/or lowers the fan speed, but the operation itself (and the status) remains unchanged. The only change is the actual hvac_mode, if I turn it on or off (or change it to cool in the summertime). So in this case the icon would always show fire (which does not bother me, tbh ;) ), but the detection of a state should probably be read from hvac_mode, not hvac_action, as for generic thermostats. If that is doable and acceptable also for other users, well, that's another question :). 
Oh, and to answer your question: last_on_operation remains "heat" even when turning the A/C off - it's simply an atttribute which tells, in which hvac_mode the A/C started the last time, so it's most likely not suitable for this case. 

Anyway, the other issue (unable to set temperature) is not related to this one as it happens also on generic thermostats, but from the code I couldn't find out, if the problem is on my side (trigger on click and scroll and calling appropriate functions seems OK to me - but I'm no programmer ;) ).

**Comment by KoalaBear84** [comment]
OK. I might also need an ice icon later, and probably also the 'dry' as well (which should be supported on my model as well, but when I use it, it doesn't really do anything) 😂

Hmm. I'm not sure how this can be fixed for the Mitsubishi. There is no way to see if it's "on" in any way? Or does it say "off" as "last\_on\_operation" when it's really off?

I'm trying to make it work for everything, also considering the icon state based on the "current\_temperature" vs the "temperature".

Do you use a comma for decimals? Like "20,1°"? Or is the Home Assistant 'server' installed on a culture that is based on a comma? (I'm checking to see why setting temperature doesn't work)

**Comment by AdmiralStipe** [comment]
Well, I can tell if it's on or off simply by checking the hvac_mode (if it's on, it says "heat" or "cool" or "dry" and if it's off, it says "off". But when it's on (in any mode), the only attributes that change during operation are: 
current_temperature (measured from sensor)
temperature (read from the device, this is set temperature, changes only if I set different temp)
current_humidity (measured from sensor)
fan_mode (read from device, depending on the fan setting, changes only if I change the fan setting)
All other attributes remain unchanged. The "last_on_operation" only changes at Mitsubishi startup depening on the selected startup mode. 
So I guess in this case (to put it differently, if the "hvac_action" attribute is missing) the on/off detection can only be made from "hvac_mode". 

And regarding comma... you might be right on spot here... on Windows I use comma (,), but on Raspberry (where Homeassistant is running), the default setting seems to be the point (.). I'm not sure if I dare to change that to experiment and confirm it (I managed to crash my HA once already with experiments like this :) ). Do we have any "softer" and less risky way to test and confirm it?
By the way, Raspbian operates with point (also in my log files all temperatures are recorded with point), but on the other hand, my WebUI and also my Android app shows commas, not points... but that might be due to regional settings on the devices.

**Comment by KoalaBear84** [comment]
Try this one, be sure to have the same HAClimateDeskBand.json in there. It will do the reading of the temperature, power usage (if available) and climate. And set temperature 0.1 higher (and lower again) and logs all responses from HA.

[HAClimateDeskBandDiagnostics.zip](https://github.com/KoalaBear84/HAClimateDeskBand/files/5807823/HAClimateDeskBandDiagnostics.zip)

Attach the HAClimateDeskBandDiagnostics.txt.

For the other things I'll look another time.

**Comment by AdmiralStipe** [comment]
After some troubles convincing Avast, that this is not a virus I managed to run it :). 
The result:
[HAClimateDeskBandDiagnostics.txt](https://github.com/KoalaBear84/HAClimateDeskBand/files/5807941/HAClimateDeskBandDiagnostics.txt)
Then I tried changing my regional WIndows settings (changed comma to point) and ran the diagnostics again. The result: 
[HAClimateDeskBandDiagnostics2.txt](https://github.com/KoalaBear84/HAClimateDeskBand/files/5807962/HAClimateDeskBandDiagnostics2.txt)

I can see, that the setting changed the line "Setting temperature 0.1 higher to 23,1.." to "Setting temperature 0.1 higher to 23.1..", but the response and effect seem the same...

**Comment by KoalaBear84** [comment]
I've possibly fixed it by always using en-US culture for the posts to HA API.

Please try this new version. Easiest is to go to the folder, already have the new version extracted in like a subfolder, kill explorer.exe, change the files, restart explorer.exe

https://github.com/KoalaBear84/HAClimateDeskBand/releases/tag/v1.2.0.2

**Comment by AdmiralStipe** [comment]
Yes, yes, it works now perfectly :): 
Now, if it would be possible to fix also my "Mitsubishi A/C" issue, that would be awesome :D. 
Oh, and by the way, since I'm handing our requests - is it possible to use more than one widget in the taskbar (and if yes, how), since I have three themostats to control at the same time?

**Comment by KoalaBear84** [comment]
Could you create 2 separate issues for this? 😂

**Comment by AdmiralStipe** [comment]
No prob, I'm sure I'm able to create more issues than you are willing to solve :).
