### ISSUE TITLE
Controlling of actual IR controlled A/C with different entity parameters

### ISSUE THREAD

**Issue by AdmiralStipe** [KoalaBear84/HAClimateDeskBand#4]
**Describe the bug**
The plugin only works for generic thermostats (a heater, connected to a smartplug and reading a temperature sensor in the room). When I try to control an "upgraded" thermostat, (actual IR controlled A/C device) the measured temp and time turn red and the error "Error retreiving/updating values: Value can not be null. Parameter name: value" shows up.
The issue is, that the plugin reads "hvac_action" from the entity for controlling the mode, but the A/C device has no "hvac_action" parameter, instead it only operates with "hvac_mode". Comparison as follows: 
Mitsubishi:
hvac_modes: off, cool, heat, dry
min_temp: 18
max_temp: 30
target_temp_step: 1
fan_modes: low, med, high, auto
current_temperature: 22.6
temperature: 23
current_humidity: 46.4
fan_mode: high
last_on_operation: heat
device_code: 88888
manufacturer: Mitsubishi Heavy
supported_models: SRK35ZJX-S
supported_controller: Broadlink
commands_encoding: Base64
friendly_name: Living room
supported_features: 9

Generic:
hvac_modes: heat, off
min_temp: 20
max_temp: 30
current_temperature: 20.7
temperature: 21
hvac_action: heating
friendly_name: Bedroom
supported_features: 1

**Expected behavior**
In this special case the widget should read/write "hvac_mode" instead of "hvac_action" to determine and set the status of the A/C device. Available modes are "off, cool, heat, dry". 
Additionally, it would be awesome if the widget could also set the "fan_mode" attribute to really have the whole control set available in the widget. Available modes for fan are "low, med, high, auto".
The described features apply to my model of A/C. Other models can possibly have other modes and/or different behaviour.

**Comment by KoalaBear84** [comment]
Wanted to look at the earlier. But tried to check it out. Sadly it is not fully clear what is the best way.

From the previous issue:

```jsonc
{
    "entity_id": "climate.kopalnica",
    "state": "heat",
    "attributes": {
        "hvac_modes": [
            "heat",
            "off"
        ],
        "min_temp": 20.0,
        "max_temp": 30.0,
        "current_temperature": 21.9,
        "temperature": 23.0,
        "hvac_action": "heating",
        "friendly_name": "Kopalnica",
        "supported_features": 1
    },
    "last_changed": "2021-01-13T07:59:13.910664+00:00",
    "last_updated": "2021-01-13T10:23:05.274556+00:00",
    "context": {
        "id": "da1025d58eb757258b44b6ba1cdb89a9",
        "parent_id": null,
        "user_id": null
    }
}
```

I see here `"state": "heat"` and `"hvac_action": "heating"`, what would be the best way?

You said it was always like this, even if it is not doing anything, correct?

Here is no info about "cool" or "dry", or is that for a different unit?

**Comment by AdmiralStipe** [comment]
Sorry for confusion... as I wrote before, I have three climates, one of them is a "real" A/C (Mitsubishi) and two of them are "virtual", that means, I have a heater connected to a smartplug and a separate temperature sensor - the smartplug and the sensor are connected to a virtual thermostat. 
So, what you are referring to here (climate.kopalnica) is a virtual one in the bathroom and yes, it is a different unit as the Mitsubishi. This one functions just fine with the plugin as it is now. This one has (at least in my case) the "hvac_mode" and "state" always at "heat" and depending on a smartplug state the "hvac_action" changes to "heating" or "idle". This is similar or even the same as your use-case, so it's OK. 

Now, the other case is Mitsubishi, which is a real climate and functions a bit different. It doesn't even use the "hvac_action" property. The only way to tell the current function is to observe the "hvac_mode", which changes regarding to the... well, mode :). And this one has also cool and dry. 

So, I'm not sure if it's even possible (and how), but there should be some kind of setting to choose, if the observed action needs to be "hvac_mode" or "hvac_action". In Mitsubishi case the plugin would observe/control the "hvac_mode" (there are more -  heat/cool/dry/off) and in other cases (virtual climate or virtual thermostats) the plugin would observe/control the "hvac_action", as the "hvac_mode" does not change in this case. 

Hopefully I have explained my issue better now... if not, let me know and I will try to elaborate further :).

**Comment by KoalaBear84** [comment]
Could you run a Diagnostics thing and attach it here? So I can see the real output.

Please run one when it's off, and one when on so I can see the difference. And maybe can use the current\_temperature \< temperature to use the 'fire' icon, at least for now because it currently only 'understands' heating.

You can write down the correct values from your current config so you can easily fill them in afterwards.

**Comment by AdmiralStipe** [comment]
Sure, I'll run the diag (but won't be home until tommorow), so it'll take me some time. 
Regarding fire icon... maybe I also didn't explain the operational mode good enough... It's not to expect from the plugin to switch between the fire and freeze icon during single operation mode, because the A/C also doesn't work that way. 
If heating mode is selected, then the A/C simply heats until the set temperature is reached and then it just stops heating and it waits. It does not change to "cool" mode, it just remains in "heat" mode, just the fan stops spinning and the heater stops heating, but the A/C still runs (kinda idle, but the status does not change to idle, it remains "heat").  
The same is with cool mode (just the opposite, of course).
 
But anyway, I'll try to run the diag in three different ways, so you'll see, how it behaves (hopefully it won't confuse you more): 
1. A/C Heating mode, current_temperature < set_temperature
2. A/C Heating mode, current_temperature > set_temperature
3. A/C Off

If all works well, we can talk about "cool" and "dry" mode later on - anyway, I wouldn't dare to switch to cool mode right now as it's below freezing point outside :).

**Comment by KoalaBear84** [comment]
Haha. Here it also is freezing since yesterday and first snow since 2 years, a 'big' layer around 10-20cm.

Yes, understood the part of heating mode. No problem, take you time :)

**Comment by AdmiralStipe** [comment]
Came home a bit earlier, so here are the logs, marked as in my previous post: 
[1_AC Heating mode, current_temperature lower than set_temperature.txt](https://github.com/KoalaBear84/HAClimateDeskBand/files/5940338/1_AC.Heating.mode.current_temperature.lower.than.set_temperature.txt)
[2_AC Heating mode, current_temperature higher than set_temperature.txt](https://github.com/KoalaBear84/HAClimateDeskBand/files/5940339/2_AC.Heating.mode.current_temperature.higher.than.set_temperature.txt)
[3_AC Off.txt](https://github.com/KoalaBear84/HAClimateDeskBand/files/5940340/3_AC.Off.txt)

There is an error present at the end of all of them, but I can't figure it out, is there something I did or is it a general error...

**Comment by AdmiralStipe** [comment]
Hopefully I don't seem impatient, but is there any progress?

**Comment by KoalaBear84** [comment]
Sorry. No you don't. It's just that my brain doesn't want to cooperate. I would like to continue ASAP. 😅

**Comment by KoalaBear84** [comment]
Sorry again.. A feel little burned-out, at least for 'complex' tasks.

Did made progress on another thing, the Installer, together with automated builds. The installer is not completely up to date yet, but the start is there. Now that is out of the way, I hope I can focus on this issue next.

**Comment by KoalaBear84** [comment]
Sorry for the long wait, hopefully it works with this. Currently only for heating. Will create a new issue where I'l add a 'snowflake' icon and implement it. But need more info for that because I don't have an airco unit connected in Home Assistant.

https://github.com/KoalaBear84/HAClimateDeskBand/releases/tag/v1.2.2.3

**Comment by AdmiralStipe** [comment]
Well, first of all thanks for your effort. 
It works, but only partially... I mean, it turns A/C on and off and controls the heating, but I'm unable to set a temperature - or to put it differently, with scrolling the wheel the commands are sent to the A/C (audible beeps from the device), but the set temperature never changes. If I change the temperature in HA, the change is immediately reflected in the DeskBand also, but the DeskBand itself can not set the temperature. 
Could it be because of the fact, that DeskBand changes the temperature by 0.1°C and the A/C is only capable of accepting integer values (f.e. 24°C, 25°C, 26°C)?

**Comment by KoalaBear84** [comment]
You're welcome.

Hmm, could be. What happens when you try to increase it in HA with 0.5? I saw that HA also made it possible to increase with 0.1 lately, before that it only did 0.5 increments.

And thanks for testing it that fast 👍

**Comment by AdmiralStipe** [comment]
I tried in HA with 0.5 and 0.1 steps... it works inside HA, but when I set a temp to f.e. 24.2, HA rounds it on 24 and sets the A/C to that. If I set it to 24.8, it rounds on 25 and sets it. Also this change to the integer is reflected in DeskBand, however decimals are not. 
But even when I have the resolution set to 0.1 or 0.5 in HA, scrolling has no other effect than an audible confirmation from the A/C (but that only means, that IR code has been transmitted) - the set temperature in HA remains unchanged all the time. 

I also ran your Diag thingy, but it shows no differences at all before and after scrolling the wheel. All the data is completely the same, except of course "last updated" time.

**Comment by KoalaBear84** [comment]
OK. Looks like I can use target_temp_step value, which is "1.0" and use that.

Try to make a new version ASAP.

**Comment by KoalaBear84** [comment]
It's should now work:

https://github.com/KoalaBear84/HAClimateDeskBand/releases/tag/v1.2.2.5

**Comment by AdmiralStipe** [comment]
Indeed it does, awesome job, thanks :).

**Comment by KoalaBear84** [comment]
Great, finally from the todo list! 😅😇
